from pathlib import Path

import numpy as np

def train_bpe(in_string: bytes | Path | str, vocab_size: int, special_tokens: list[str]) -> tuple[dict[int, bytes], list[tuple[bytes, bytes]]]: ...

class BPETokenizer:
    def __new__(
        cls,
        vocab: dict[int, bytes],
        merges: list[tuple[bytes, bytes]],
        special_tokens: list[str] | None = None,
    ) -> "BPETokenizer": ...
    def encode(self, text: bytes) -> np.typing.NDArray[np.uint16]: ...
    def decode(self, tokens: np.typing.NDArray[np.uint16]) -> str: ...
    @classmethod
    def from_tiktoken(cls, path: str) -> "BPETokenizer": ...

class PretokenizerIterator:
    def __init__(self, text: bytes): ...
    def __iter__(self): ...
    def __next__(self) -> bytes: ...

def pretokenizer(text: bytes) -> PretokenizerIterator: ...
