from pathlib import Path

def train_bpe(
    in_string: bytes | Path | str,
    vocab_size: int,
    special_tokens: list[str],
) -> tuple[dict[int, bytes], list[tuple[bytes, bytes]]]: ...

class BPETokenizer:
    def __new__(cls) -> "BPETokenizer": ...
    def encode(self, text: bytes) -> list[int]: ...
    @staticmethod
    def from_tiktoken(path: str) -> "BPETokenizer": ...
    def __repr__(self) -> str: ...

class LlamaTokenizer:
    @staticmethod
    def from_hf(path: str) -> "LlamaTokenizer": ...
    def encode(self, text: str) -> list[int]: ...
    def encode_no_normalize(self, text: str) -> list[int]: ...
    def decode(self, tokens: list[int]) -> bytes: ...
    def __repr__(self) -> str: ...

class PretokenizerIter:
    def __iter__(self) -> "PretokenizerIter": ...
    def __next__(self) -> bytes: ...

def pretokenizer(text: bytes) -> PretokenizerIter: ...
def pretokenized_counts(text: bytes) -> list[tuple[bytes, int]]: ...
